<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website Header</name>
   <tag></tag>
   <elementGuidId>b06753f0-31c2-44fb-84f1-65aaaf5dbff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.header.headerSortUp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table1']/thead/tr/th[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>b69e8e94-292b-45e5-aeef-be86e182ebb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header headerSortUp</value>
      <webElementGuid>f05a7699-3875-491a-9e96-756e34ed5a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Web Site</value>
      <webElementGuid>7db37fd3-0fbd-46c7-9b06-b00c0aef9ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table1&quot;)/thead[1]/tr[1]/th[@class=&quot;header headerSortUp&quot;]</value>
      <webElementGuid>7d7e9de4-a8d7-4eb2-8c08-4b68de21c7b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table1']/thead/tr/th[5]</value>
      <webElementGuid>59e42cbc-3ab1-44d8-b479-ec787a7e9155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due'])[1]/following::th[1]</value>
      <webElementGuid>8d35058d-e81d-4ef6-bc3c-d2d8128783af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::th[2]</value>
      <webElementGuid>159a38d8-f62a-4002-9d38-e11321849700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::th[1]</value>
      <webElementGuid>90c6689d-fe29-4f69-81a8-be644f8ba34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]</value>
      <webElementGuid>32fd53a5-f006-47b7-bf3a-f202970aec22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Web Site' or . = 'Web Site')]</value>
      <webElementGuid>7897c477-d30f-4b19-b1ba-5fea497eb14e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
